name: Despliegue a Surge.sh

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Instalar Surge.sh
        run: npm install -g surge

      - name: Despliegue a Surge.sh
        run: surge --project . --domain SamirSpraud.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
